name: test nodl_python

on:
  pull_request:
    paths: 
      - '**.py'
  push:
    branches: 
      - master
  schedule:
    - cron: '0 * * * *'

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    steps:
    - uses: ros-tooling/setup-ros2@0.0.11
    - uses: ros-tooling/action-ros2-ci@0.0.11
      with: 
        package-name: nodl_python
    - uses: actions/upload-artifact@master
      with:
        name: colcon-logs
        path: ros2_ws/log
      if: always()
