name: test nodl

on:
  pull_request:
    paths:
      - '**.py'
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    steps:
    - uses: ros-tooling/setup-ros2@0.0.12
    - uses: ros-tooling/action-ros-ci@0.0.13
      with:
        package-name: nodl_python
    - uses: actions/upload-artifact@v1
      with:
        name: colcon-logs
        path: ros_ws/log
      if: always()
